Application · PROPERTIES
spring.application.name=Veterinaria

# Conexión PostgreSQL (Supabase) mediante variables de entorno
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.hpkubcguxwbhspmovtsa
spring.datasource.password=HsRss1wjLXhKBdPI
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Render asigna el puerto en la variable PORT; en local usa 8081
server.port=${PORT:8081}

