spring.application.name=Veterinaria


# Configuración de Conexión MySQL en Docker
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.hpkubcguxwbhspmovtsa
spring.datasource.password=vXo5uATCGSc3p1YV
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

